### ISSUE TITLE
About file slice

### ISSUE THREAD

**Issue by Sunny-NEU** [Honghe/iflytek_asr_python#1]
Hi, i'm grateful for the python implementation of the iflytek_ifasr,which is very useful for me, and it works well. However, I don't understand the meaning of the operation getting file sliced,which you slice the file into several small slices and  merge them later. The ifly can deal with audio file  within 5 hours. Could you tell me about this?

**Comment by Honghe** [comment]
The `merge` is called to inform the Server to merge the slices and transcribe the audio.
